### ISSUE TITLE
Unexpected result when called with code that cannot be optimised

### ISSUE THREAD

**Issue by lokedhs** [charJe/tailrec#1]
Consider the following code:

```
(tailrec:tailrec
  (defun foo (n)
    (print n)
    (when (plusp n)
      (foo (1- n)))
    (print 'end)))
```

This compiles with no warnings, but prints the following:

```
4
3
2
1
0
END
```

The result without `TAILREC` is:

```
4
3
2
1
0
END
END
END
END
END
```

I believe that either the example code should fail to compile, or it should not try to optimise it so it behaves the same as the non-optimised version.

**Comment by charJe** [comment]
Thanks for reporting this. `foo` is not tail recursive, so tailrec should not optimize and report that it is not tail recursive. I'll look into it.

**Comment by charJe** [comment]
[9d15227](https://github.com/charJe/tailrec/commit/9d15227133a0402b6b973a5cdc59f9518e599e85) shoud fix it. You can close this issue if that works for you
