### ISSUE TITLE
Remove Destructuring-bind

### ISSUE THREAD

**Issue by charJe** [charJe/tailrec#4]
@phoe
> Also, I see that you use destructuring-bind in there - destructuring long argument lists might be a net negative for performance, and I assume that you could avoid doing this (as well as avoid duplicating the body in the macroexpansion) by parsing recursive calls and the defined function's lambda list, and explicitly setting function arguments before the go call.

I'll have to look into this. I didn't do it initially because argument lists can get pretty complex and destructuring bind gets the job done.

**Comment by phoe** [comment]
From the lambda list, you can get all the arguments you need via `alexandria:parse-ordinary-lambda-list`, and then based on that you should be able to figure out how to `setf` them when you analyze the recursive calls.
